### ISSUE TITLE
DSQL Expression don't consume DateTime

### ISSUE THREAD

**Issue by DarkSide666** [atk4/data#263]
**FabulousGee:**

Since I updated from 1.2.1 to 1.2.2 yesterday, the following code does not work anymore:
```
$this->todayDateTime = new \DateTime('now', new \DateTimeZone('UTC'));
$this->todayDateTime->setTime(0,0);

$m = new DienstplanModel($db);
$m->tryLoadBy('Date',  $this->todayDateTime);
```

It throws the following error:
```
Only Expressions or Expressionable objects may be used in Expression

[vendor/atk4/dsql/src/Query.php:687] atk4\dsql\Expression->_consume(DateTime::__set_state(['date'=>'2017-12-14 00:00:00.000000','timezone_type'=>3,'timezone'=>'UTC']),'param')
[vendor/atk4/dsql/src/Query.php:705] atk4\dsql\Query->__render_where('where')
[vendor/atk4/dsql/src/Expression.php:419] atk4\dsql\Query->_render_where()
[vendor/atk4/dsql/src/Expression.php:429] preg_replace_callback('/\[[a-z0-9_]*\]|{[a-z0-9_]*}/',Closure::__set_state([]),'select[option] [field] [from] [table][join][where][group][having][order][limit]')
[vendor/atk4/dsql/src/Query.php:1183] atk4\dsql\Expression->render()
[vendor/atk4/dsql/src/Expression.php:523] atk4\dsql\Query->render()
[vendor/atk4/dsql/src/Expression.php:631] atk4\dsql\Expression->execute()
[vendor/atk4/data/src/Persistence_SQL.php:702] atk4\dsql\Expression->getRow()
```

Imants:
I also got similar error with latest release. As workaround we can use format() again:
`$m->tryLoadBy('Date',  $this->todayDateTime->format('Y-m-d'));`

**Comment by DarkSide666** [comment]
Functions like `load`, `tryLoad` etc. should use type casting of value depending on field `type`.
Not sure if it does that already.

**Comment by romaninsh** [comment]
how come it used to work...

**Comment by romaninsh** [comment]
Typecasting code for "addCondition" which is used by loadBy and tryLoadBy is here: https://github.com/atk4/data/blob/develop/src/Persistence_SQL.php#L344

**Comment by romaninsh** [comment]
@FabulousGee, please confirm and that 'Date' field is added using `['type'=>'date']`. If you do use it, here is what happens:

`tryLoadBy` will store Datetime object inside $model->conditions[]. This is then picked up by `Persistence_SQL` (note that other persistences may not support this) and this supposed to change the value SQL-friendly format. Because this does not happen, object remains object as it is passed into `where`

Unfortunately `where` will also store the object without converting it into a string, because it things that it might be expression. I have added ticket to address that on low level: https://github.com/atk4/dsql/issues/121

**Comment by romaninsh** [comment]
Added new test https://github.com/atk4/data/commit/741f34d5f4b5ba9b36dc0b0dee2bfb149134290d#diff-e0c535c2db3cf837a5c1b295aa07e298R244 which demonstrate a properly working DateTime typecasting. Tests pass successfully.
