### ISSUE TITLE
Should action('xyz')->execute() trigger hooks?

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/data#291]
Hi there,

I just stumbled across this:
```
if($grtt->loaded()) {
    $grtt->delete();
}
```
beforeDelete Hook is triggered

```
if($grtt->loaded()) {
    $grtt->action('delete')->execute();
}
```

beforeDelete Hook is **not** triggered.
Is this intended behaviour?

Best regards
Philipp

**Comment by DarkSide666** [comment]
Well yes that's intended behaviour because `action()` uses DSQL and it can be anything (any query) of which Model is not aware. That's why DSQL will not have such hooks anymore.

So you always, if at all possible, have to stick to Model methods not DSQL queries. That way you will have less surprises and your code will be cleaner and safer for future changes.

**Comment by romaninsh** [comment]
Yes, that is correct. The approach above is similar to executing direct query. It's much faster, but each record data won't be available and all records will be deleted simultaniously. 

Technically we could have 'beforeDeleteQuery' or 'beforeDeleteAction' but there is no policy on how to do it. Something to consider for implementing across all actions.

**Comment by PhilippGrashoff** [comment]
Hi,

thanks for the info!
