### ISSUE TITLE
Typecasting for id field

### ISSUE THREAD

**Issue by roelleor** [atk4/data#293]
It makes sense to me that id fields can be typecasted. For example, auto increment ids are expected to be normalized to integers.

**Comment by romaninsh** [comment]
if you set type on id field, it will probably be typecasted. I haven't tested it though. Thing with ID is that even if it's numeric, you don't expect it to behave like a number, so it's not a huge deal. 

We specifically have a type-less fields which are capable of storing number or int. I'll close this ticket because it does not explain an actual problem case but is more of an idea.

If you find an actual problem related to id field typecasting, please open new ticket.

**Comment by roelleor** [comment]
Ok, I will try to set the type on the id field (I thought that wasn’t possible). I like to do strict comparison where possible that’s why I like an integer to actually be one,  thats all.
