### ISSUE TITLE
Traverse relation in Expressions

### ISSUE THREAD

**Issue by romaninsh** [atk4/data#341]
Currently only [existing] [fields] can be used. We want to make it possible to traverse relations:

If your Model has a link 'client_id' to 'Client' - we can make it traversable:

```
[client_id.name]
// or
[client.name]
```

This would result in `refLink('client_id')->action('field', ['name']);`

The syntax can also be used for `hasMany('Items', new Item())` relations:

```
sum([Items.price])
```

**Comment by mvorisek** [comment]
@georgehristov ping

**Comment by georgehristov** [comment]
This is an old issue and I believe already addressed with latest PRs on Scope / link traversing

**Comment by mvorisek** [comment]
yes, closing, and never allow `client_id.name` (traverse on _id field)

API stability issues comes from a) not using industry standard principes/tools, b) not refactorable code/string. So do everything we can to satisfy both, otherwise do not introduce any new functionality, as it will change sooner or later...
