### ISSUE TITLE
Escaped quote issue

### ISSUE THREAD

**Issue by roelleor** [atk4/data#349]
Not sure if this is a ui or data bug:
I'm using MasterCRUD + Ui + Data, all in the latest version. Persistence is MySQL.
When I programmatically set an Atk4/Model's field that contains a quote, e.g.: monkey's banana, everything words fine. However, setting this through a basic MasterCRUD ui, the single quote get's stored with an additional escape, e.g.: monkey\\'s banana. Pressing 'save' again will add an additional escape, e.g.: monkey\\\\'s banana

**Comment by romaninsh** [comment]
@roelleor try this:

1. clone atk/data into fresh folder (develop)
2. add new example under tests/*.php illustrating the bug
3. add assert which would fail due to this bug.

If you are unable to do that, then it's not a bug in ATK Data. If it still is a problem, open new issue with evidence. Thanks!
