### ISSUE TITLE
Possible Bug: addField problem with plural table names

### ISSUE THREAD

**Issue by acicovic** [atk4/data#407]
Hi,
ATK lesson 12 in Udemy introduces aggregation. Here is what we add in Friend.php to aggregate loans:

    $ref = $this->hasMany('Loans', new Loan());
    $ref->addField('total_loan', ['aggregate' => 'sum', 'field' => 'amount']);

This works fine when table names are singular (loan, friend). However, if we update table names to "loans", "friends" and also update $table variable within related models we get an error.

```
Exception Parameters
model: Object Models\Loan
field: "friends_id"

_html\atk\vendor\atk4\data\src\Model.php: 874 | atk4\data\Exception | atk4\core\Exception::__construct
-- | -- | --  | ( "Field does not exist")
\vendor\atk4\data\src\Reference_Many.php: 78 | Models\Loan | atk4\data\Model::addCondition()

```

Here ATK searches for the non-existing field "friends_id" which is normally "friend_id".

Is this reproducible at your end? Perhaps there's a parameter to overcome this?

**Comment by funyx** [comment]
yep .. atk4/data/Reference_hasMany is trying to load the relation using predefined rules, in that case it will search `friends_id` as foreign (key) field because the referenced model Loan has the following property set : 
- public $table = 'friends';
.. thus the field can be represented as :
```
$field = ($Loan->table) . '_' . ($Friend_model->id_field);
```

if the field is named differently you should specify it in the Ref definition:

```
$ref = $this->hasMany('Loans', [
  new Loan(),
  'their_field' => 'friend_id'
]);
$ref->addField('total_loan', ['aggregate' => 'sum', 'field' => 'amount']);
```
