### ISSUE TITLE
UI Form and loadBy() causes problems: loadBy sets field to 'system => true' what makes the field disappear

### ISSUE THREAD

**Issue by PhilippGrashoff** [atk4/data#409]
Hi there,

this is a rather complicated one. Follow this UI code:
```
$model = new SomeModel($this->app->db);
$model->tryLoadBy(`someField`, `someValue`);
$form = $this->add(`Form`);
$form->setModel($model);
```

If you want to have that field `someField` displayed it won't work, because `loadBy()` uses `addCondition()`, whichs sets `someField` to `system => true`. With `system => true` the Field is neither `isEditable()` nor `isVisible()`.

As this is quite complicated and as there is surely some good reason to set the field to `system => true`, in `addCondition()` its questionable if there is a sensible fix for this.
The best workaround seems to set `ui => ['visible' => true]` to the field.

Once found its easy to work around, but quite confusing when the field suddenly isnt shown :)

**Comment by romaninsh** [comment]
I agree this is a bug. Reasoning:

addCondition makes sure that record would not be saved outside of allowed value, therefore Form would not be allowed to change "someField" even if it wouldn't be system.

tryLoadBy sets a TEMPORARY condition only. The condition is removed after record is loaded. Therefore there is no reason fro "someField" to remain system.

@DarkSide666 would you agree with this?

The modification can be done in "loadBy" to restore "system" flag to how it was before condition was set.

**Comment by PhilippGrashoff** [comment]
Sounds quite sensible to me.

**Comment by DarkSide666** [comment]
Looks OK. Need to be fixed in `loadBy` and `tryLoadBy` and also needs to restore field `default` value property.
I was thinking about introducing new (maybe only internal) method `addTemporaryCondition` and `removeTemporaryCondition` or something like that to avoid code duplication.
Also need to remember that `$field` property can also be just a string - field name, so it would be good to somehow avoid all that code duplicating.

I will work on that.

**Comment by DarkSide666** [comment]
Fixed in https://github.com/atk4/data/pull/410
