### ISSUE TITLE
Way to order non-english language data names?

### ISSUE THREAD

**Issue by enderlen** [atk4/data#518]
Hi,

I'm trying to order by name data displayed in a Grid...

For such names ['Électricité', 'Finance'] I get ascending order 'Finance' then 'Électricité' as it is basically processed as English content...

So I tried some code in app initialization:
`$this->db->connection->connection()->sqliteCreateCollation('French', 'strcoll');`
then
`$model->setOrder('name COLLATE French ASC');`
but without any success

What would be best way to create and use a collation with ATK data ?

**Comment by PhilippGrashoff** [comment]
As the order of the records is defined by the database, I wonder if the issue is in there. Is the collation of the according table set correctly? If you are working on the DB directly, do the results show up in the order wanted?
As far as I understand ATK has nothing to do with the order of the records, as they are used one by one from the result returned by the DB query.

**Comment by DarkSide666** [comment]
Ordering of data in Grid is implemented as purely backend solution. That means, that data is sorted by SQL itself.
Not sure about sqlite, but in mysql you have to:
1. set proper character encoding in your DB connection string
2. set proper character set in your database settings
Then it should work as expected.

**Comment by enderlen** [comment]
My SQLite database is UTF-8, and as far as I understand, there no way to define and store collation settings in such database, so it should be created for each connection (https://sqlite.org/datatype3.html#collation).

In my other PHP programs, I'm used to rely on this code that works perfectly:
```
		$db = new PDO($dsn);
		setlocale(LC_COLLATE, 'fr_FR.UTF-8');
		$db->sqliteCreateCollation('French', 'strcoll');
```

But it seems non operant when trying:

**Comment by DarkSide666** [comment]
How your DSN string ($dsn variable) looks like?

**Comment by DarkSide666** [comment]
So what your lines in other PHP programs does is that `sqliteCreateCollation('French', 'strcoll')` defines new collation function in SQLite named 'French' which will use PHP `strcoll` function for comparing values. Also you have set `setlocale` in php to fr_FR.UTF-8 collation, so it will use it for comparing values.

Most likely in SQL queries (or maybe in connection string) you define, that you use `COLLATION French`, right?

I guess you can do all of that in Agile Toolkit too.
In worst case you can initialize PDO object yourself like you're doing in other programs and pass it to `connect()` method instead of $dns string.
And then use expression in `setOrder()` probably like this:
```
$m->setOrder($m->expr('{} COLLATE French ASC', [$m->getField('name')]));
```

**Comment by enderlen** [comment]
Ok thks a lot, issue was the setOrder call, this now all works using your expression
`$m->setOrder($m->expr('{} COLLATE French ASC', [$m->getField('name')]));`
instead of my previous call that don't work:
`$->setOrder('name COLLATE French ASC');`

even if I don't exactly understand difference between the 2...

**Comment by enderlen** [comment]
My $dsn is 
`sqlite:../../db/app.db`

Yes I do want to use `COLLATE French` in individual SQL queries

I tried this syntax 
`$m->setOrder($m->expr('{} COLLATE French ASC', [$m->getField('name')]));`
instead of 
`$m->setOrder('name COLLATE French ASC');`
with same result.

What's seems to be is Collation sequence French is defined with the call:
`$this->db->connection->connection()->sqliteCreateCollation('French', 'strcoll');`
because when I comment this code, I then get an error :
```
PDOException Error
PDOException [code: HY000] SQLSTATE[HY000]: General error: 1 no such collation sequence: French
```
But when collation created, no error at all, but just english order

**Comment by enderlen** [comment]
Also creating manually an external PDO object with collation and then "attaching" it to app with `connect()` results the same behavior

**Comment by DarkSide666** [comment]
Did you add `setlocale(LC_COLLATE, 'fr_FR.UTF-8');` line in your php code?

**Comment by enderlen** [comment]
yes I did

**Comment by DarkSide666** [comment]
:( Then I have no idea. You have to try to debug your SQL and/or try same thing in some test script and/or SQL console. Also try adding some var_dump in your code and check for php locale setting.

**Comment by enderlen** [comment]
I made several other tests, and I was very disappointed to see code isn't working on my dev workstation but... finally working perfectly when published on website !

Locally I was using MAMP with 7.3 php version while website was 7.2 php version.

So I've downgraded PHP version from 7.3 to 7.2 and all this collation stuff is now working as expected with the code from first posted message...

This was just my last think it is a PHP version issue...

Anyway thks for your help ;)
