### ISSUE TITLE
Merge atk4\schema in atk4\data

### ISSUE THREAD

**Issue by georgehristov** [atk4/data#635]
Proposal for merging atk4\schema in atk4\data

Under the new namespace structure the merged folder will be under:

`Presistence\Sql\Schema`
`Presistence\Sql\Schema\Migration.php`
`Presistence\Sql\Schema\Migration\Mysql`
etc.

**Comment by DarkSide666** [comment]
Maybe.
The question is - how/why it will be better than it is currently? :)

**Comment by georgehristov** [comment]
I have so far 3 arguments:
- it can then be used in data production code (for model scope operations like checking if a record is within a scope)
- it is already required in data dev dependencies
- will make data more complete package as migration is often part of data manipulation so devs do not have to search/require another package.

**Comment by mvorisek** [comment]
> it can then be used in data production code (for model scope operations like checking if a record is within a scope)

wdym?

> Proposal for merging atk4\schema in atk4\data

I used `schema` once and it is very unmature lib. I fixed there some general issues in past, but basic things like foreign keys are not supported yet and implementation is not that easy because the update order is critical.

So for SQL, I think we should something like Doctrine migrations.

Actually, I think we should implement data on Doctrine. I think it is possible to extend Doctrine to offer all needed functionality.

So I do not think it should be integrated.

I also think we should drop Array persistence in advance to in-memory sqlite and use Sql backend for it - wdyt?
