### ISSUE TITLE
Rename Persistence\Array_ to Persistence\Memory

### ISSUE THREAD

**Issue by georgehristov** [atk4/data#689]
Using `Persistence\Memory` or `Persistence\Variable` is more logical as to 'where' the data is saved not 'in what format' (e.g `Persistence\Sql` being `Persistence\Table`)
Good side-effect is we will not use php reserved word for the class name.

We can then introduce `Persistence\Session extends Persistence\Memory`.
I think no need to explain what it will do. This is the benefit of explicit names.

**Comment by mvorisek** [comment]
Hmm, I am quite ok with Array as array/hash table is the backend

Memory is ok with me, but breaking... definitely not `Persistence\Variable`

**Comment by mvorisek** [comment]
Closing this issue because of feedback from @DarkSide666

more feedback from my side:
- in PHP8, we can use `Array` because of https://wiki.php.net/rfc/namespaced_names_as_token
- `Persistence\Memory` is not a good name because `memory` is reserved Sqlite backend name
- https://github.com/atk4/data/issues/699
